services:
  mysql:
    image: mysql:latest
    container_name: mysql_sb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votacao
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: no

  app:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/votacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: no

volumes:
  mysql_data:
