services:
  front:
    build:
      context: ./desafio-votacao-front
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "80:80"
    restart: no

  back:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/votacao
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: no

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: votacao
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: no
    command: --bind-address=0.0.0.0
volumes:
  mysql_data:

